# ashyterm/settings/colors.py
# Extracted from config.py → color schemes + scheme map

from functools import lru_cache
from typing import Any, Dict, List


class ColorSchemes:
    """Terminal color schemes."""

    @staticmethod
    @lru_cache(maxsize=1)
    def get_schemes() -> Dict[str, Dict[str, Any]]:
        return {
            "system_default": {
                "name": "System Default",
                "foreground": "#ffffff",
                "background": "#000000",
                "headerbar_background": "#1a1a1a",
                "cursor": "#ffffff",
                "palette": [
                    "#000000",
                    "#cc0000",
                    "#4e9a06",
                    "#c4a000",
                    "#3465a4",
                    "#75507b",
                    "#06989a",
                    "#d3d7cf",
                    "#555753",
                    "#ef2929",
                    "#8ae234",
                    "#fce94f",
                    "#729fcf",
                    "#ad7fa8",
                    "#34e2e2",
                    "#eeeeec",
                ],
            },
            "biglinux": {
                "name": "BigLinux",
                "foreground": "#e6e6e6",
                "background": "#0a0a0a",
                "headerbar_background": "#1c1c1c",
                "cursor": "#e6e6e6",
                "palette": [
                    "#444444",
                    "#ed4545",
                    "#11d164",
                    "#f6ca5a",
                    "#5c7aff",
                    "#d26cc9",
                    "#39acf3",
                    "#dcdfe4",
                    "#7f8888",
                    "#f56b66",
                    "#4ef384",
                    "#ffeda2",
                    "#85a6ff",
                    "#f48bea",
                    "#6dccff",
                    "#ffffff",
                ],
            },
            "light": {
                "name": "Light",
                "foreground": "#000000",
                "background": "#ffffff",
                "headerbar_background": "#f0f0f0",
                "cursor": "#000000",
                "palette": [
                    "#000000",
                    "#cc0000",
                    "#4e9a06",
                    "#c4a000",
                    "#3465a4",
                    "#75507b",
                    "#06989a",
                    "#555753",
                    "#888a85",
                    "#ef2929",
                    "#8ae234",
                    "#fce94f",
                    "#729fcf",
                    "#ad7fa8",
                    "#34e2e2",
                    "#eeeeec",
                ],
            },
            "dark": {
                "name": "Dark",
                "foreground": "#ffffff",
                "background": "#1c1c1c",
                "headerbar_background": "#2a2a2a",
                "cursor": "#ffffff",
                "palette": [
                    "#000000",
                    "#cc0000",
                    "#4e9a06",
                    "#c4a000",
                    "#3465a4",
                    "#75507b",
                    "#06989a",
                    "#d3d7cf",
                    "#555753",
                    "#ef2929",
                    "#8ae234",
                    "#fce94f",
                    "#729fcf",
                    "#ad7fa8",
                    "#34e2e2",
                    "#eeeeec",
                ],
            },
            "solarized_light": {
                "name": "Solarized Light",
                "foreground": "#657b83",
                "background": "#fdf6e3",
                "headerbar_background": "#eee8d5",
                "cursor": "#657b83",
                "palette": [
                    "#073642",
                    "#dc322f",
                    "#859900",
                    "#b58900",
                    "#268bd2",
                    "#d33682",
                    "#2aa198",
                    "#eee8d5",
                    "#002b36",
                    "#cb4b16",
                    "#586e75",
                    "#657b83",
                    "#839496",
                    "#6c71c4",
                    "#93a1a1",
                    "#fdf6e3",
                ],
            },
            "solarized_dark": {
                "name": "Solarized Dark",
                "foreground": "#839496",
                "background": "#002b36",
                "headerbar_background": "#073642",
                "cursor": "#839496",
                "palette": [
                    "#073642",
                    "#dc322f",
                    "#859900",
                    "#b58900",
                    "#268bd2",
                    "#d33682",
                    "#2aa198",
                    "#eee8d5",
                    "#002b36",
                    "#cb4b16",
                    "#586e75",
                    "#657b83",
                    "#839496",
                    "#6c71c4",
                    "#93a1a1",
                    "#fdf6e3",
                ],
            },
            "monokai": {
                "name": "Monokai",
                "foreground": "#f8f8f2",
                "background": "#272822",
                "headerbar_background": "#3a3b34",
                "cursor": "#f8f8f2",
                "palette": [
                    "#272822",
                    "#f92672",
                    "#a6e22e",
                    "#f4bf75",
                    "#66d9ef",
                    "#ae81ff",
                    "#a1efe4",
                    "#f8f8f2",
                    "#75715e",
                    "#f92672",
                    "#a6e22e",
                    "#f4bf75",
                    "#66d9ef",
                    "#ae81ff",
                    "#a1efe4",
                    "#f9f8f5",
                ],
            },
            "dracula": {
                "name": "Dracula",
                "foreground": "#f8f8f2",
                "background": "#282a36",
                "headerbar_background": "#3a3c4e",
                "cursor": "#f8f8f2",
                "palette": [
                    "#000000",
                    "#ff5555",
                    "#50fa7b",
                    "#f1fa8c",
                    "#bd93f9",
                    "#ff79c6",
                    "#8be9fd",
                    "#bfbfbf",
                    "#4d4d4d",
                    "#ff6e67",
                    "#5af78e",
                    "#f4f99d",
                    "#caa9fa",
                    "#ff92d0",
                    "#9aedfe",
                    "#e6e6e6",
                ],
            },
            "nord": {
                "name": "Nord",
                "foreground": "#d8dee9",
                "background": "#2e3440",
                "headerbar_background": "#3b4252",
                "cursor": "#d8dee9",
                "palette": [
                    "#3b4252",
                    "#bf616a",
                    "#a3be8c",
                    "#ebcb8b",
                    "#81a1c1",
                    "#b48ead",
                    "#88c0d0",
                    "#e5e9f0",
                    "#4c566a",
                    "#bf616a",
                    "#a3be8c",
                    "#ebcb8b",
                    "#81a1c1",
                    "#b48ead",
                    "#8fbcbb",
                    "#eceff4",
                ],
            },
            "tokyonight": {
                "name": "Tokyo Night",
                "foreground": "#c0caf5",
                "background": "#1a1b26",
                "headerbar_background": "#1f2335",
                "cursor": "#c0caf5",
                "palette": [
                    "#15161e",
                    "#f7768e",
                    "#9ece6a",
                    "#e0af68",
                    "#7aa2f7",
                    "#bb9af7",
                    "#7dcfff",
                    "#a9b1d6",
                    "#414868",
                    "#f7768e",
                    "#9ece6a",
                    "#e0af68",
                    "#7aa2f7",
                    "#bb9af7",
                    "#7dcfff",
                    "#c0caf5",
                ],
            },
            "catppuccin": {
                "name": "Catppuccin Mocha",
                "foreground": "#f5e0dc",
                "background": "#1e1e2e",
                "headerbar_background": "#181825",
                "cursor": "#f5e0dc",
                "palette": [
                    "#45475a",
                    "#f38ba8",
                    "#a6e3a1",
                    "#f9e2af",
                    "#89b4fa",
                    "#f5c2e7",
                    "#94e2d5",
                    "#bac2de",
                    "#585b70",
                    "#f38ba8",
                    "#a6e3a1",
                    "#f9e2af",
                    "#89b4fa",
                    "#f5c2e7",
                    "#94e2d5",
                    "#cdd6f4",
                ],
            },
            "rose_pine": {
                "name": "Rosé Pine",
                "foreground": "#e0def4",
                "background": "#191724",
                "headerbar_background": "#1f1d2e",
                "cursor": "#ebbcba",
                "palette": [
                    "#26233a",
                    "#eb6f92",
                    "#9ccfd8",
                    "#f6c177",
                    "#31748f",
                    "#c4a7e7",
                    "#ebbcba",
                    "#e0def4",
                    "#6e6a86",
                    "#eb6f92",
                    "#9ccfd8",
                    "#f6c177",
                    "#31748f",
                    "#c4a7e7",
                    "#ebbcba",
                    "#e0def4",
                ],
            },
            "pink_light": {
                "name": "Pink Light",
                "foreground": "#4a2040",
                "background": "#ffe4ec",
                "headerbar_background": "#ffd0dd",
                "cursor": "#d63384",
                "palette": [
                    "#4a2040",
                    "#d63384",
                    "#198754",
                    "#cc7a00",
                    "#0d6efd",
                    "#8b5cf6",
                    "#0dcaf0",
                    "#6c757d",
                    "#5c3d52",
                    "#e83e8c",
                    "#20c997",
                    "#ffc107",
                    "#6ea8fe",
                    "#a78bfa",
                    "#6edff6",
                    "#495057",
                ],
            },
        }


class ColorSchemeMap:
    """Maps combobox indices to color scheme names."""

    SCHEME_ORDER = [
        "system_default",
        "biglinux",
        "light",
        "dark",
        "solarized_light",
        "solarized_dark",
        "monokai",
        "dracula",
        "nord",
        "tokyonight",
        "catppuccin",
        "rose_pine",
        "pink_light",
    ]

    @classmethod
    def get_schemes_list(cls) -> List[str]:
        return cls.SCHEME_ORDER.copy()
